#!/usr/bin/env python
"""
40_md_provenance.py -- harvest MD run provenance and write it INTO the README.

Why this exists
---------------
The MD replicates use ig=-1, so pmemd draws a fresh random seed for each run.
That is deliberate (it is what makes the replicates independent samples), but it
means the trajectories are not reproducible from the scripts alone. pmemd records
the seed it actually used in each stage's .out file, so reproducibility is
recoverable -- provided the seeds are captured before those files are cleaned up
or overwritten by a resubmission.

This script harvests, per system and replicate:
    * the random seed of every MD stage (heat, eq1, eq2, prod)
    * measured throughput (ns/day) and wall time
    * which stages completed, and how much production actually accumulated
    * the GPU the run landed on
and rewrites the block between the MD_PROVENANCE markers in README.md.

It is idempotent and safe to re-run at any time: run it while jobs are in flight
to see progress, and again at the end to freeze the final record.

Usage:  python 40_md_provenance.py [--no-readme]
"""
import argparse, glob, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MD = os.path.join(ROOT, "data", "md")
README = os.path.join(ROOT, "README.md")
LOGS = os.path.join(ROOT, "logs")
START = "<!-- MD_PROVENANCE_START -->"
END = "<!-- MD_PROVENANCE_END -->"
STAGES = ["min1", "min2", "heat", "eq1", "eq2", "prod"]

ap = argparse.ArgumentParser()
ap.add_argument("--no-readme", action="store_true",
                help="print only; do not modify README.md")
args = ap.parse_args()


def scan(out):
    """seed, ns/day, simulated ns, wall seconds from an Amber mdout."""
    d = {}
    try:
        txt = open(out, errors="ignore").read()
    except OSError:
        return d
    # ig=-1 means pmemd DRAWS a seed at runtime and announces it; the echoed
    # namelist still reads "ig = -1", so match the announcement first.
    m = re.search(r"Setting random seed to\s+(\d+)", txt)
    if not m:
        m = re.search(r"^\s*ig\s*=\s*(\d+)\s*$", txt, re.M)
    if m and m.group(1) != "-1":
        d["seed"] = int(m.group(1))
    m = re.findall(r"ns/day\s*=\s*([0-9.]+)", txt)
    if m:
        d["ns_day"] = float(m[-1])
    m = re.findall(r"TIME\(PS\)\s*=\s*([0-9.]+)", txt)
    if m:
        d["ps"] = float(m[-1])
    m = re.search(r"Total wall time:\s*([0-9]+)\s*seconds", txt)
    if m:
        d["wall_s"] = int(m.group(1))
    return d


rows = []
systems = sorted(d for d in os.listdir(MD) if os.path.isdir(os.path.join(MD, d))
                 and d.startswith("S"))
for s in systems:
    for rep_dir in sorted(glob.glob(os.path.join(MD, s, "rep*"))):
        rep = os.path.basename(rep_dir)
        rec = dict(system=s, rep=rep, seeds={}, done=[], ns_day=None,
                   prod_ns=0.0, gpu="")
        for st in STAGES:
            o = os.path.join(rep_dir, f"{st}.out")
            if os.path.exists(os.path.join(rep_dir, f"{st}.rst7")):
                rec["done"].append(st)
            info = scan(o)
            if "seed" in info:
                rec["seeds"][st] = info["seed"]
            if st == "prod":
                if "ns_day" in info:
                    rec["ns_day"] = info["ns_day"]
                if "ps" in info:
                    rec["prod_ns"] = info["ps"] / 1000.0
        # continuation runs
        for o in sorted(glob.glob(os.path.join(rep_dir, "prod_cont*.out"))):
            info = scan(o)
            if "seed" in info:
                rec["seeds"].setdefault("prod_cont", info["seed"])
            if "ps" in info:
                rec["prod_ns"] = max(rec["prod_ns"], info["ps"] / 1000.0)
        rows.append(rec)

# GPU model per array task, from the SLURM logs
for lg in glob.glob(os.path.join(LOGS, "md_*.log")):
    try:
        txt = open(lg, errors="ignore").read()
    except OSError:
        continue
    m = re.search(r"=== task (\d+) : (\S+) replicate (\d+) ===", txt)
    g = re.search(r"(NVIDIA [A-Za-z0-9\- ]+)", txt)
    if m and g:
        for r in rows:
            if r["system"] == m.group(2) and r["rep"] == f"rep{m.group(3)}":
                r["gpu"] = g.group(1).strip()

lines = []
if not rows:
    lines.append("*No MD output yet — jobs have not started writing. "
                 "Re-run `scripts/40_md_provenance.py` once they do.*")
else:
    n_done = sum(1 for r in rows if "prod" in r["done"])
    lines.append(f"**Run provenance** (generated by `scripts/40_md_provenance.py`) — "
                 f"{len(rows)} replicate directories, {n_done} with production "
                 f"complete.\n")
    lines.append("| system | rep | stages complete | production | ns/day | GPU |")
    lines.append("|---|---|---|---|---|---|")
    for r in rows:
        nsd = f"{r['ns_day']:.1f}" if r["ns_day"] else "—"
        lines.append(f"| {r['system']} | {r['rep']} | {len(r['done'])}/6 | "
                     f"{r['prod_ns']:.1f} ns | {nsd} | {r['gpu'] or '—'} |")

    lines.append("\n**Random seeds** — `ig=-1` draws these at runtime; recording "
                 "them is what makes an individual trajectory reproducible. To "
                 "repeat a run exactly, set `ig=<seed>` in the corresponding "
                 "stage input.\n")
    lines.append("| system | rep | " + " | ".join(STAGES[2:]) + " |")
    lines.append("|---|---|" + "---|" * len(STAGES[2:]))
    for r in rows:
        cells = [str(r["seeds"].get(st, "—")) for st in STAGES[2:]]
        lines.append(f"| {r['system']} | {r['rep']} | " + " | ".join(cells) + " |")

block = "\n".join(lines)
print(block)

if not args.no_readme:
    txt = open(README).read()
    if START in txt and END in txt:
        pre = txt.split(START)[0]
        post = txt.split(END)[1]
        open(README, "w").write(pre + START + "\n" + block + "\n" + END + post)
        print(f"\nupdated the MD provenance block in {README}")
    else:
        print(f"\n!! markers not found in {README}; nothing written")
